(ns clojure.scene2d.actor
  (:refer-clojure :exclude [name]))

(defmulti create :type)

(defprotocol Actor
  (set-opts! [_ opts])
  (name [_])
  (x [_])
  (y [_])
  (width [_])
  (height [_])
  (stage->local-coordinates [_ vector2])
  (add-listener! [_ listener])
  (user-object [_])
  (stage [_])
  (set-name! [_ name])
  (set-user-object! [_ object])
  (set-position! [_ [x y]]
                 [_ x y align])
  (set-visible! [_ visible?])
  (set-touchable! [_ touchable])
  (visible? [_])
  (hit [_ [x y] touchable?])
  (remove! [_])
  (parent [_])
  (toggle-visible! [_])
  (find-ancestor [_ ui-type-k])
  (button? [_] "Returns true if the actor or its parent is a button.")
  (window-title-bar? [_]))
