(ns clojure.gdx.input.keys
  (:import (com.badlogic.gdx Input$Keys)))

(def left   Input$Keys/LEFT)
(def right  Input$Keys/RIGHT)
(def up     Input$Keys/UP)
(def down   Input$Keys/DOWN)
(def minus  Input$Keys/MINUS)
(def equals Input$Keys/EQUALS)
(def enter  Input$Keys/ENTER)
(def p      Input$Keys/P)
(def space  Input$Keys/SPACE)
(def escape Input$Keys/ESCAPE)
(def i      Input$Keys/I)
(def e      Input$Keys/E)
(def d      Input$Keys/D)
(def a      Input$Keys/A)
(def w      Input$Keys/W)
(def s      Input$Keys/S)
