(ns com.badlogic.gdx.input$keys
  (:import (com.badlogic.gdx Input$Keys)))

(def D Input$Keys/D)
(def A Input$Keys/A)
(def W Input$Keys/W)
(def S Input$Keys/S)
(def MINUS Input$Keys/MINUS)
(def EQUALS Input$Keys/EQUALS)
(def P Input$Keys/P)
(def SPACE Input$Keys/SPACE)
(def ESCAPE Input$Keys/ESCAPE)
(def I Input$Keys/I)
(def E Input$Keys/E)
(def ENTER Input$Keys/ENTER)
(def LEFT Input$Keys/LEFT)
(def RIGHT Input$Keys/RIGHT)
(def UP Input$Keys/UP)
(def DOWN Input$Keys/DOWN)
