(ns moon.graphics)

(defprotocol Graphics
  (unproject-ui [_ position])
  (update-ui-viewport! [_ width height])
  (clear-screen! [_ color])
  (set-cursor! [_ cursor-key])
  (draw! [_ draws])
  (draw-tiled-map! [_ tiled-map color-setter])
  (frames-per-second [_])
  (delta-time [_])
  (dispose! [_])
  (position [_])
  (visible-tiles [_])
  (frustum [_])
  (zoom [_])
  (change-zoom! [_ amount])
  (set-position! [_ position])
  (world-vp-width [_])
  (world-vp-height [_])
  (unproject-world [_ position])
  (update-world-vp! [_ width height])
  (draw-on-world-vp! [_ f]))
