(ns moon.ui)

(declare skin)

(defprotocol UserInterface
  (dispose! [_])
  (show-data-viewer! [_ data])
  (viewport-width  [_])
  (viewport-height [_])
  (get-ctx [_])
  (mouseover-actor [_ position])
  (action-bar-selected-skill [_])
  (inventory-window-visible? [_])
  (toggle-inventory-visible! [_])
  (show-modal-window! [_ skin ui-viewport {:keys [title text button-text on-click]}])
  (set-item! [_ cell item-properties])
  (remove-item! [_ inventory-cell])
  (add-skill! [_ skill-properties])
  (remove-skill! [_ skill-id])
  (show-text-message! [_ message])
  (toggle-entity-info-window! [_])
  (close-all-windows! [_])
  (show-error-window! [_ skin throwable])
  (actor-information [_ actor]))
