(ns clojure.gdx
  (:require clojure.gdx.input
            clojure.gdx.scenes.scene2d.actor
            clojure.gdx.scenes.scene2d.group
            clojure.gdx.scenes.scene2d.event
            clojure.gdx.scenes.scene2d.ui.widget
            clojure.gdx.scenes.scene2d.ui.scroll-pane
            clojure.gdx.scenes.scene2d.ui.horizontal-group
            clojure.gdx.scenes.scene2d.ui.label
            clojure.gdx.scenes.scene2d.ui.image-button
            clojure.gdx.scenes.scene2d.ui.select-box
            clojure.gdx.scenes.scene2d.ui.stack
            clojure.gdx.scenes.scene2d.ui.image
            clojure.gdx.scenes.scene2d.ui.text-button
            clojure.gdx.scenes.scene2d.ui.text-field
            clojure.gdx.scenes.scene2d.ui.text-tooltip
            clojure.gdx.scenes.scene2d.ui.table
            clojure.gdx.scenes.scene2d.ui.image
            clojure.gdx.scenes.scene2d.ui.check-box
            clojure.gdx.scenes.scene2d.ui.window
            clojure.gdx.scenes.scene2d.ui.widget-group
            clojure.gdx.scenes.scene2d.utils.texture-region-drawable
            clojure.gdx.scenes.scene2d.utils.change-listener
            clojure.gdx.scenes.scene2d.utils.click-listener
            clojure.gdx.maps.map-layers
            clojure.gdx.maps.map-properties
            clojure.gdx.maps.tiled.tiled-map
            clojure.gdx.maps.tiled.tiled-map-tile-layer
            clojure.gdx.utils.disposable))
