(ns clojure.malli-form-register-methods
  (:require [clojure.malli-form-s-animation]
            [clojure.malli-form-s-boolean]
            [clojure.malli-form-s-enum]
            [clojure.malli-form-s-image]
            [clojure.malli-form-s-map]
            [clojure.malli-form-s-number]
            [clojure.malli-form-s-one-to-many]
            [clojure.malli-form-s-one-to-one]
            [clojure.malli-form-s-qualified-keyword]
            [clojure.malli-form-s-some]
            [clojure.malli-form-s-sound]
            [clojure.malli-form-s-string]
            [clojure.malli-form-s-val-max]
            [clojure.malli-form-s-vector]))
