(ns moon.grid2d.utils-test
  (:require [moon.game :as game])
  (:import (java.util Random)))
(comment
 (let [{:keys [start grid]} (game/caves-create (Random.) 15 15 :wide)
       _ (println "BASE GRID:\n")
       _ (game/print-y-up grid)
       ;_ (println)
       ;_ (println "WITH START POSITION (0) :\n")
       ;_ (g2d/print-y-up (assoc grid start 0))
       ;_ (println "\nwidth:  " (g2d/width  grid)
       ;           "height: " (g2d/height grid)
       ;           "start " start "\n")
       ;_ (println (g2d/posis grid))
       _ (println "\n\n")
       filled (game/flood-fill grid start (fn [p] (= :ground (get grid p))))
       _ (game/print-y-up (reduce #(assoc %1 %2 nil) grid filled))])
 )
